services:
  app:
    container_name: trabalho_app
    env_file:
      - ./app/.env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/var/www/html
    networks:
      - trabalho-network
    depends_on:
      - db  

  db:
    image: mysql:8.0
    env_file:
       - ./app/.env
    ports:
      - "4000:3306"
    volumes:
      - /sql
      - /var/lib/mysql
    networks:
      - trabalho-network  

  nginx:
    build:
      context: .docker/nginx
    volumes:
      - ./app:/var/www/html:delegated
      - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - .docker/nginx/sites:/etc/nginx/sites-available
      - .docker/nginx/conf.d/:/etc/nginx/conf.d
    ports:
      - '8000:80'
    networks:
      - trabalho-network
    depends_on:
      - app

networks: 
  trabalho-network:
  
volumes: 
  db: